server:
  port: 8087

spring:
  datasource:
    username: root
    password: rootroot
    url: jdbc:mysql://localhost:3306/confjour?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
  sql:
    init:
      mode: never

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8085/eureka/
