server:
  port: 8087

spring:
  datasource:
    username: 
    password: 
    url: jdbc:mysql://host.docker.internal:3306/confjour?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
  sql:
    init:
      mode: never

eureka:
  client:
    service-url:
      defaultZone: http://host.docker.internal:8085/eureka/
