server:
  port: 5274

spring:
  datasource:
    username: SWArchi
    password: 123ppp456
    url: jdbc:mysql://host.docker.internal:3306/parter?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
  sql:
    init:
      mode: never

eureka:
  client:
    service-url:
      defaultZone: http://host.docker.internal:5272/eureka/
