spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 750MB

server:
  port: 8088 # 端口号自己配新的，不要重复
  servlet:
    encoding:
      force-response: false
      charset: UTF-8

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8085/eureka/

springfox:
  documentation:
    enabled: false

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

application:
  auth:
    url: http://AUTH-SERVICE/
    default-url: http://localhost:8086/
  confjour:
    url: http://CONFJOUR-SERVICE/
    default-url: http://localhost:8087/
