server:
  port: 5273

spring:
  datasource:
    username: SWArchi
    password: 123ppp456
    url: jdbc:mysql://localhost:3306/auth?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
  sql:
    init:
      mode: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:5272/eureka/
